# Generated by Django 3.2.9 on 2021-11-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_storefile_mediafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefile',
            name='file_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='storefile',
            name='mediaFile',
            field=models.FileField(upload_to=''),
        ),
    ]
