# Generated by Django 3.2.9 on 2021-11-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211114_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEncoder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_Url', models.URLField(blank=True)),
                ('media_type', models.CharField(max_length=10)),
            ],
        ),
    ]
