# Generated by Django 3.2.9 on 2021-11-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_dataencoder'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncodedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dash_output', models.URLField(blank=True)),
                ('hls_output', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='dataencoder',
            name='output_location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dataencoder',
            name='segment_folder',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dataencoder',
            name='File_Url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataencoder',
            name='media_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
