# Generated by Django 3.2.9 on 2021-11-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20211114_2223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataEncoder',
            new_name='DataEncoder_Settings',
        ),
    ]
