# Generated by Django 3.2.9 on 2021-11-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_rename_dataencoder_dataencoder_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataencoder_settings',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
